Azimer/AziAudio

AziAudio/ABI_Adpcm.cpp

All of the inputs initialize the same way more or less. Among the three ABI functions, there are minor differences in the parameters.

Initialize all inputs in a single function

---

AziAudio/ABI_Resample.cpp

Increment accum variable

---

AziAudio/XAudio2SoundDriver.cpp

XAudio2SoundDriver: Fix duplicate conditions

---

AziAudio/ABI3mp3.cpp

The InnerLoop in ABI3mp3 is extremely bloated as of now. First, I separated a block of code into a separate function. Then the actual multiplication is separated into another function.

Separate Dewindow function

---

AziAudio/ABI3mp3.cpp

In the InnerLoop of ABI3mp3, there are a lot of comments where you store a value from the array v into the array mp3data. I think a function would make the code a lot clearer and possibly reduce the extra comments.

Add a function to save a value into mp3data

---

AziAudio/ABI3mp3.cpp

This should clean up some of the initialization code and make it easier to work with.

Add a function to get mp3data values

---

AziAudio/ABI_Envmixer.cpp

Made a small change in each commit. I added a 16-bit and 32-bit version of two functions only because I wasn't sure if it was necessary or not.

Added helper functions to EnvMixer

---

AziAudio/ABI_Envmixer.cpp
AziAudio/DirectSoundDriver.cpp
AziAudio/SoundDriver.h
AziAudio/XAudio2SoundDriver.cpp
AziAudio/main.cpp

As pointed out by Frank-74 here, https://github.com/Azimer/AziAudio/pull/58, my method of resolving the merge conflict with my last pull request was a bit uneducated...I hope that with the entire merge done in this commit it should have the rest of everything back to the way it was.  Sorry for any confusion I've caused people.
I was supposed to notice earlier but got caught up in other projects, RDP stuff.

Merge the rest of the other contribs, not just the conflict resolution.

---

AziAudio/AziAudio.xbx.vcproj
AziAudio/XBox/xbox_depp.cpp
AziAudio/XBox/xbox_depp.h

commits are self-explanatory. :)

Get Xbox project building again

---

AziAudio/ABI_Adpcm.cpp

I was confused about the lack of any apparent check for a negative shift amount into issuing a question about it here:  https://github.com/Azimer/AziAudio/issues/66#issuecomment-101811260
I think with these minor changes to the comments to refer to look all the way up to the function that is actually using the `vscale` value at all will help prevent this confusion.

Referred rcp's comments to the negative shift check in InitInput.

---

AziAudio/ABI_Envmixer.cpp

There's a lot of multiplication, bitshifting, addition, etc. going on in that function. With so many buffers being used, it definitely would help to use a function.

Simplify ENVMIXER2

---

AziAudio/ABI_Adpcm.cpp

Okay this one was very challenging and time-consuming for me.  It wasn't the hardest SSE work I've ever done in any plugin, but so far in this plugin it was the most tricky for me to implement.
I say "almost the entirety".  A few things left are like, memcpy...things totally insignificant to gains in performance compared to this function I have touched.
Got to say I was under the pressure of time trying to finish up--do let me know if there is anything to nitpick.  Needless to say it is more complex than for me to just be happy naming a couple games I can regression test, so it can need more testing.

vectorized almost the entirety of what's left of ABI_Adpcm.cpp

---

AziAudio/ABI_Adpcm.cpp

I spoke too soon.
Went to bed after the last PR, woke up, suddenly thought of some more crazy ideas.
Tested again with Zelda and Mario very quickly.  The `InitInput` function can be vectorized too, later.

moar xmm's plz

---

AziAudio/ABI_Filters.cpp

After I saw the new filter implemented just recently to support some sound effects going on in _PilotWings_ or whatever I immediately saw a couple things to vectorize about it.  However I have done no regression-testing whatsoever, because I don't know of any games that use PilotWings ucode (heard something about Body Harvest, StarFox maybe?  bunch of games that weirded me out never really had any motive to get familiar with them).
In case there is a regression, this is why I do multiple commits.  It's also nice to show my work step-by-step; that was one of my favorite things to do in math classes. :)

completed SSE2 optimizations on new bsmiles code in POLEF()

---

AziAudio/AziAudio.vcproj
make_w32.cmd

Update VS2008 project

---

AziAudio/ABI_Envmixer.cpp

The function was actually multiplying fractional numbers, so I added documentation to the function and changed its name to indicate its real purpose.

Rename MixVol to MultQ15

---

AziAudio/ABI_Envmixer.cpp

There's a few places where an if statement exists inside another if statement. In certain cases, a *single* `if` statement with *multiple* conditions could replace *multiple* `if` statements with a *single* condition. This reduction is allowed when multiple `if` statements do the same thing.

Reduce the number of if statements

---

AziAudio/DirectSoundDriver.cpp

I am not able to tell by testing what bug (if any) this fixes, but it looks like a bug.

fixed warning (and probably bug) about assignment in condition

---

AziAudio/main.cpp

o hay guyz!
I couldn't help but notice there is a Linux port of this plugin.
So I wanted to improve portability a little by getting it to compile on Windows, too.
lol sorry about the regression, I kept meaning to fix it the past few weeks but never expected Azimer would beat me and merge, just had a few delays with being able to boot into Git on my laptop
Anybody who notices anything different about the Windows build as a result of my Linux changes, please do let me know.

Port AziAudio to Windows.

---

AziAudio/SoundDriver.h
AziAudio/main.cpp

I kept the same default settings.  Saves and loads sync settings, AI Emulation setting, and volume level, to Config\AziCfg.bin.

Cheap Save/Load config settings

---

AziAudio/XAudio2SoundDriver.cpp
AziAudio/XAudio2SoundDriver.h

I forgot to fix the XA2 volume.

Fix XA2 volume

---

AziAudio/ABI_Envmixer.cpp

Fix HLE volume problem #178

---

AziAudio/AziAudio.vcxproj
AziAudio/AziAudio.vcxproj.filters
AziAudio/DirectSoundDriverLegacy.cpp
AziAudio/DirectSoundDriverLegacy.h
AziAudio/NoSoundDriver.cpp
AziAudio/NoSoundDriver.h
AziAudio/SoundDriver.cpp
AziAudio/SoundDriverFactory.cpp
AziAudio/SoundDriverFactory.h
AziAudio/SoundDriverLegacy.cpp
AziAudio/SoundDriverLegacy.h
AziAudio/XAudio2SoundDriverLegacy.cpp
AziAudio/XAudio2SoundDriverLegacy.h
AziAudio/common.h
AziAudio/main.cpp

Part 2 of 3 to implement swappable audio backends

SoundFactory implemented

---

AziAudio/Configuration.cpp
AziAudio/Configuration.h

Just to be on the safe side, I've re-uploaded the PR from https://github.com/Azimer/AziAudio/pull/199.
Not sure what happened.  Seems there may have been a merge conflict while Azimer was merging the others then he added a commit to my fork to fix the conflicts somehow.  It appears like it's still good, but to be safe I did a clean re-clone and re-fork of the repo to base these commits on.

Recreate PR #199.
