AziAudio/main.cpp

This was all zilmar's original code for the function really; like every audio plugin uses it.  I just felt like it could be more readable to remove any potential distraction from things like, a bug in the main CPU emulator passing an invalid SystemType to the function, or oddball values of AI_DACRATE_REG.  I also felt like it may be more readable to invert the if { } else { } branch predictor so that the entire, much larger else { } bit doesn't all have to be indented an extra tab.  (See very first commit.)
Mostly a bunch of idealistic, minor changes, though I think it could help document some bits more.
So, for a few years now, I've always been curious what would happen on real hardware if a game managed in some way to access the reserved/unused bits of RCP registers.  For example, it's …

rewrote plugin spec function AiDacrateChanged

---

AziAudio/ABI2.cpp
AziAudio/ABI3.cpp
AziAudio/WaveOut.cpp
AziAudio/WaveOut.h

All the warning messages when compiling should be fixed now.
At times I'm sure some warnings are better left unfixed, than fixed, but I think with what few cases (only seemed to be 4 warnings left in this entire source) were left, it seemed straightforward enough to tackle.

fixed all the level 3 MSVC compiler warnings

---

AziAudio/ABI1.cpp
AziAudio/ABI2.cpp
AziAudio/ABI3.cpp
AziAudio/ABI3mp3.cpp
AziAudio/DirectSoundDriver.cpp
AziAudio/Mupen64plusHLE/Mupen64Support.c
AziAudio/SoundDriver.h
AziAudio/audiohle.h
AziAudio/common.h
AziAudio/main.cpp
AziAudio/mytypes.h
gccbuild/dx_mingw/dsound.h
gccbuild/dx_mingw/xaudio2.h
make_w32.cmd

I wanted to give it a try to see how hard it might be to get this plugin to compile using MinGW.  I was afraid it would be a wasted effort, but actually it just took a few changes (less than 20 generally small and divided commits, outlined below).
I guess I'm mostly a portability geek, so it was partly for fun, but then again, there are both pros and cons to linking Windows binaries with MinGW instead of Microsoft Visual C++.  (50% of the time I'd say the pros outweigh the cons 100% of the time.)  At the very least, it opens up the possibility for testing the plugin built by a different compiler, which might help isolate whether some bugs are problems in the C++ code or unspecified behavior that varies between compiler to compiler.
Unfortunately, I do not have `XAudio2.h` handy on me in …

got the plugin to compile in MinGW GCC/G++

---

AziAudio/DirectSoundDriver.cpp
AziAudio/XAudio2SoundDriver.cpp

If you have no sound card or you're like me and accidentally yank your headphones unplugged every once in a while, you may have noticed that this plugin (either in DirectSound or XAudio2 mode) will crash at various points as early as when starting a ROM and as late as when shutting down the emulation thread.  This pull request is meant mostly to just address that.
It doesn't fix this issue still:
https://github.com/Azimer/AziAudio/issues/3
I know because I boot up Rogue Squadron, but it's hung up waiting for an interrupt from the audio interface.  This happens when sound is playing, but not when playing with my headphones unplugged.

Prevent all the XAudio2 and DirectSound crashing when playing with no sound.

---

AziAudio/XAudio2SoundDriver.cpp

The crash occurred on line #230, when booting up WDC.

Fix initialization problem in WDC with XA2

---

AziAudio/DirectSoundDriver.cpp

Without Sleep(1), a whole cpu core is used up, without any noticeable
benefit, afaik.

Add Sleep(1) to AudioThreadProc in DS8

---

make_w32.cmd

Frank74 pointed out a few things I overlooked while making the build script.  I have not used XP in a while so wasn't aware until now.
The only unresolved thing is the GUI (and still no XAudio2)...I can't figure out why it's not working.  I did at least include the resource script in the linker config this time though, which I forgot to do last time.  I use the same config on my angrylion RDP plugin to get the GUI to work, but why it doesn't work here, I'm not sure.  May be different rules when linking C++ objects than C objects or something.

MinGW build fixes for some old versions of Windows

---

AziAudio.sln
AziAudio/AziAudio.vcxproj
AziAudio/main.cpp

I'm somewhat disappointed at how few changes it took to get it to build as a 64-bit DLL.  Turns out all I really needed to do was fix a function pointer mismatch in the resource dialog creation (first commit) and add the x64 stuff in the solution file to do the build (third commit).  There are 2 or 3 warnings left, but I fixed one of them as a demonstration (second commit).  I guess the easiest thing to do there seemed to be to factor in that the volume setting never exceeds a value of 100 decimal, so just clamp it to that and then force an explicit type-cast to DWORD anyway.  (Not sure that there was any better solution?)
Anyway what I'm stuck on is this linker error I'm getting in Release mode:
```
1>MSVCRT.lib(ti_inst.obj) : fatal error LNK1112: module machine type 'X86' conflicts with …
```

got 64-bit Debug builds working in VS2013 Community

---

AziAudio/resource.rc

This mostly is a repeat of an idea we've tested successfully with the Project64 repo:
https://github.com/project64/project64/pull/78
Back then I had learned from searching on the web that most people discovered that:
```c
#include "afxres.h"
```
... could be replaced with ...
```c
#include <WinResrc.h>
#define IDC_STATIC   (-1)
```
The missing afxres.h error is one you might find through searching online enough, but I remember Frank74 and I ran into it personally from the more lightweight installations of VS we did.  (I think there was supposed to be some optional checkbox when installing MSVC that would give you the afxres header.)  At any rate, the interwebz general consensus seems to be that the replacement is safe, and prevents the risk of compiler errors.  I did this change to get …

Make compiling easier for people with Express/minimalist VS packages.

---

AziAudio/XAudio2SoundDriver.cpp

Modifying a variable twice across a sequence point is considered undefined behavior.

XAudio2SoundDriver: Get rid of undefined behavior

---

AziAudio/XAudio2SoundDriver.cpp

This seems to fix the unnecessary sample rate conversion in XAudio2, making it sound tinny and thin when lots of samples are playing.

Fix XAudio2 sample degradation

---

AziAudio/ABI_Filters.cpp

Well, here's one that I spent a few more hours on.  Now that the rest of the source has been addressed enough to my liking, I decided to start cleaning up some RSP stuff.  I was most interested in `ABI_Filters.cpp` because I thought it made use of the vector shuffle operands, but it turned out to be 16-bit mixed-/bi-endianness within 32-bit word vector tricks in LWC2 pack operations.  (Man those suck.)  In the end I was able to make a function out of most of that.
I'm not sure yet which games use ABI2 ucode, though, but I'll try to figure that out in the meantime to verify the consequences of my changes.  Ever since the very first commit, I already started to think a little regression testing wouldn't hurt.  I'll address any bugs in these commits if they exist.

Vectorize some nasty LWC2/transpose and MAC stuff in ABI_Filters.cpp.

---

AziAudio/DirectSoundDriver.cpp
AziAudio/SoundDriver.h
AziAudio/XAudio2SoundDriver.cpp
AziAudio/main.cpp

Not too sure about this one for a couple reasons, but I wanted to see how appropriate it could be to just have a function to address the code complication issue mentioned here?  https://github.com/Frank-74/AziAudio/commit/300d8523c1b51c2b38f5efde762d2f96e75b63bf#commitcomment-11086246
There may be a static, branch-free approach at this too, but atm it's just a function for portability.
Aside from the risk of maintenance with explicit type-cast conversions, my uncertainty with these commits lies in this field here from the comments that I replaced:
```c
} else if (Frequency < 15000 && Frequency > 10000) {
Frequency = 11025;
```
Here, `Frequency` could be 14999 (almost 4000 Hz more than the original 11025-Hz target approximation) and get saturated to 11025 as a result of this block, but if …

Have frequency-rounding performed on leveled intervals, through a function.

---

AziAudio/common.h

Maybe a bit messy with the final macro layout, but, eh, could potentially have some improvement if more than 2 audio APIs were supported and version number got updated frequently, or maybe people might prefer sprintf.

Only need to change 1 line instead of 2 to update version numbers.

---

AziAudio/ABI_Filters.cpp
AziAudio/HLEMain.cpp
AziAudio/audiohle.h

I ran these changes quickly by a full race in _Mario Kart 64_ and _Legend of Zelda:  Ocarina of Time_ and have yet to hear any audible differences, surprisingly.  I do find that surprising, since this is my very first time I have written SIMD using the unusual _mm_madd_epi16 intrinsic:  https://msdn.microsoft.com/en-us/library/yht36sa6%28v=vs.90%29.aspx
(See the fourth commit here for its installation.)
That is where the biggest performance gain comes in.  I'm not sure how much of a bottleneck this portion of RSP audio HLE is, but this function is VERY much faster without repeated scalar multiplies, followed by repeated scalar adds, within a function called 8 times, within a loop repeated at least 16 times.  Makes a big difference.  In fact, I see no remaining ways to increase the …

folded almost the entirety of the array multiplies/adds in ABI_Filters

---

AziAudio/ABI3mp3.cpp
AziAudio/ABI_Adpcm.cpp
AziAudio/ABI_Envmixer.cpp

Several places throughout the source is the `int` data type, where at least 32 bits of precision is needed.  (For example, sometimes the plugin loads an `int` with a 16-bit data type, but later throughout the source accumulates it with 32-bit products from multiplying other elements, in which case we still require 32 bits.)
Again further regression-testing will likely be necessary here, which I have not yet completed.
The only way that saying `int` instead of `int32_t`/`s32`/whatever can be guaranteed to be safe in all cases is by the C89 rule that if you're storing something between -32768 to +32767 (in a 16-bit range), it's required to fit into an `int`.  Still, that's not a very self-explanatory thing, and if 32 bits are required we should indeed have a 32-bit type.  (Preferably a …

Use s32/i32 instead of int, when size matters.

---

AziAudio/ABI3mp3.cpp

Thanks to samuelyuan we now have already a functional allocation of the repeated behavior of storing the MP3 data as 16-bit segments.  However, the function bears such a striking resemblance to the SH op-code on the RSP, that I felt like re-doing this function to match the syntax of the SH instruction.
SH (store halfword) has the RSP assembly language syntax:
```asm
SH      $rt, +/-offset($base)
```
Naturally since SP DMEM has only 4096 (0xFFF + 1) bytes, whether the offset is positive signed or negative signed isn't exactly significant (could be either an offset of -1 or 0xFFFF, or just 0xFFF for +4095 and still end up meaning the same operation); however that doesn't change the fact that it's still a s16.  I wanted to emulate this in the new function.
As stated in a commit I've tested …

Refer to RSP hardware operation `SH` when storing halfwords.

---

AziAudio.vs2008.sln
AziAudio/AziAudio.vcproj

Frank74 found that the header note VS Express threw in was causing 2008 Professional to complain upon attempts at opening the solution -- https://github.com/Azimer/AziAudio/issues/29#issuecomment-101888939 -- so I changed it to use the standard VS2008 header which seems to work for both of us.
I also made a couple changes based on differences I spotted between project64/AziAudio and Azimer/AziAudio, but the solution file itself seems to now be basically identical to the one downstream that zilmar has going on, so at least that matches now.

Update Visual Studio 2008 solution with some fixes/match downstream.

---

AziAudio/ABI_Adpcm.cpp
AziAudio/ABI_Filters.cpp
AziAudio/HLEMain.cpp
AziAudio/audiohle.h

Before pushing these commits, I tested audio in _Super Mario 64_ and _Legend of Zelda:  Ocarina of Time_.  (Also made sure, I can break ADPCM on purpose and make audio sound like garbage, to make sure testing was set up right.)
Ultimately the purpose here is to change the 3 ADPCM loader function loops from:
```c
for (u32 x = 0; x < ((k0 & 0xffff) >> 0x4); x++) {
adpcmtable[0x1 + (x << 3)] = table[0];
adpcmtable[0x0 + (x << 3)] = table[1];
adpcmtable[0x3 + (x << 3)] = table[2];
adpcmtable[0x2 + (x << 3)] = table[3];
adpcmtable[0x5 + (x << 3)] = table[4];
adpcmtable[0x4 + (x << 3)] = table[5];
adpcmtable[0x7 + (x << 3)] = table[6];
adpcmtable[0x6 + (x << 3)] = table[7];
table += 8;
}
```
... to ...
```c
for (i = 0; i < limit; i++)
swap_elements(&adpcmtable[8*i], &table[8*i]);
```
What does …

Buffer ADPCM 128 bits at a time, rather than 16 bits at a time.

---

AziAudio/ABI_Adpcm.cpp

Further questions I had with the source discussed already at:  https://github.com/Azimer/AziAudio/issues/66#issuecomment-102144485
The last commit is my next question.  Read from un-mapped RDRAM addresses seems to result in reading an unconditional 0, so if we did `addr & 0x7FFFFF` we would break this hardware-accurate behavior just to prevent reading from a 16-megabyte address when only 8 MB RDRAM exists.  So I think it is better to leave the address unmasked hence the last commit, or could this be something to assert?

some slight readability changes to ADPCM unit

---

AziAudio/ABI_Adpcm.cpp

I felt like showing a commit for this, because the negative shift amount actually happens in DK64.
It was discussed earlier in this issue:  https://github.com/Azimer/AziAudio/issues/66
... that we should be able to change ...
```c
void InitInput(s32 *inp, int index, u8 icode, u8 mask, u8 shifter, u8 code, u8 srange, int vscale)
{
inp[index] = (s16)((icode & mask) << shifter);
if (code < srange)
inp[index] = (inp[index] * vscale) >> 16;
else
int catchme = 1;
}
```
... to ...
```c
void InitInput(s32 *inp, int index, u8 icode, u8 mask, u8 shifter, int vscale)
{
inp[index] = (s16)((icode & mask) << shifter);
inp[index] = (inp[index] * vscale) >> 16;
}
```
However it turns out that removing the `if (code < srange)` check from the InitInput function broke ADPCM3 which you can hear by booting …

Enable the negative shift amount assertion in ADPCM3.

---

AziAudio/AudioSpec.h
AziAudio/main.cpp

Due to the fact that Project64 2.x uses "RomOpen", the function
"RomOpened" is never used. Now RomOpen works. Hopefully this may help
with tracking down bugs :smile: .

Change RomOpened to RomOpen

---

AziAudio/ABI_Envmixer.cpp

I noticed that in the previous pull request #70, we made use of the pack_signed function to reduce a lot of clutter while still maintaining readability (i.e. we turned 3 lines of code into a single line by removing a <code>temp</code> variable)
In the main loop of EnvMixer3(), it is incrementing <code>out[MES(y)], aux1[MES(y)]</code>, etc. I was thinking that instead of having all those temporary variables like <code>o1</code> and <code>a1</code>, why not replace it with one line of addition using the pack_signed function?

Compressed code in EnvMixer

---

AziAudio/ABI_Adpcm.cpp

Rewriting some of the while loops with for loops makes it clearer that the loop is initializing pairs of inputs, meaning for each even <code>i</code> from 0 to 8, initialize <code>inp[i]</code> and <code>inp[i + 1]</code>.
Also made a minor change where
<code>
a[MES(j)] >>= 11; a[MES(j)] = pack_signed(a[MES(j)]);
</code>
becomes
<code>
a[MES(j)] = pack_signed(a[MES(j) >> 11]);
</code>

Condensed loops in ADPCM

---

AziAudio/ABI_Adpcm.cpp
AziAudio/HLEMain.cpp

This should be much better for performance as well as smaller functions sizes...pretty sure I lost 1 KB off the DLL size.  I tested every commit with Zelda64 and Mario at the end but didn't really think to test for regressions beyond that since I operated on the assumption that this stuff was common to all games.  (Not to mention I did in fact find regressions already and fix them before making each next commit.)
The only `for` loop left after this change now is this:
```c
for (int i = 0; i < 8; i++)
a[i] = a[i] >> 11;
```
Nothing necessitates rewriting that to SSE because auto-vectorization is incredibly simple.  There's no excuse why an optimizing Intel compiler shouldn't compile that as a PSRAD xmm0, 11 or whatever.

optimized the main ADPCM buffer input operations

---

AziAudio/ABI_Envmixer.cpp

Since the BuffValueIncr function in EnvMixer is just one-line addition, it should just be removed, since it's adding more overhead without making it any easier to maintain. I am thinking there are other functions that might need to be removed, but this should be a good start for now.

Remove one line addition function

---

AziAudio/ABI_Resample.cpp

Resample hasn't been touched much, so now is a good time to make changes. I applied the pack_signed function as well as a few other small changes. 
Note that most of the calculations take place in <code>MultAddLUT</code>, formerly called IncrAccum. I had to change the function name for IncrAccum because it was potentially misleading, given that there were two variables <code>accum</code> and <code>Accum</code> (just a small difference involving lowercase and uppercase). <code>accum</code> is more of a temp variable, but it has nothing to do with <code>Accum</code>. I renamed it to <code>MultAddLUT</code> since the function was doing multiplication and addition, but feel free to change it to a more appropriate name if needed.

Compress resample

---

AziAudio/ABI_Filters.cpp

This fixes the irritation in the background of the audio for games like _GoldenEye 007_.
It seems to have been caused by unhealthy practices of non-char pointer aliasing.
This does not include a fix for the remaining, quieter and harder to notice, fuzzy sound in the background.  To fix that as well, change:
```c
for (i = 0; i < 8; ++i)
frame[i] = inp[i];
```
to
```c
for (i = 0; i < 8; ++i)
frame[i] = inp[i ^ 1];
```
... which was what Azimer was going to do but said he wouldn't commit yet since the fix didn't have any noticeable effect.  I think the effect will be more noticeable after the louder, more noticeable issue fixed with this commit is done.
I didn't include a commit to fix it to inp[i ^ 1] in this pull request either because that will create a conflict with the other pull …

Fix POLEF background noise agitation.

---

AziAudio/ABI_Filters.cpp

Turns out all of the SSE code was correct.  I did nothing wrong (based on the observation that audio sounds fine now) except that xmm_source was meant to still be the old value it was set to before, _mm_set1_epi16(Gain).  After the first iteration of the loop after that point, xmm_source got re-defined as a temporary register to accumulate other products to it.
There was a quick fix to this and a "faster" fix; I chose the latter.
The quick fix would be to force xmm_source = Gain every loop iteration, but the commit I did instead names a new variable, xmm_gain, to solve the collision that way and reuse old values.

fix to the SSE2 codepath for POLEF()

---

AziAudio/HLEMain.cpp
AziAudio/audiohle.h

This worked on MSVC but not necessarily in other cases, so the INLINE hint is temporarily off limits with externally linked symbols.
From what I have seen MSVC will still automatically select these functions for in-line expansion anyway.

Let compiler decide whether to in-line procs with external linkage.

---

AziAudio/ABI3mp3.cpp

Few observations:
v[0]...v[15] gets data from the array mp3data via multiple xor operations (to be exact, it's 
in the form `v[i] = GetData(2 * (i ^ (i / 2) ^ (i / 4) ^ (i / 8)))`. 
v[16]....v[31] gets data in the form `v[i] = GetData(2 * i).
The way the values are set up, there is a lot of swapping among a pair of elements. I wrote out all the values and expanded
Just for a concrete example...
`v[0] = GetData(2 * (0 ^ 0 ^ 0 ^ 0)) = GetData(0x00)`
`v[1] = GetData(2 * (1 ^ 0 ^ 0 ^ 0)) = GetData(2 * 1) = GetData(0x02)`
`v[2] = GetData(2 * (2 ^ 1 ^ 0 ^ 0)) = GetData(2 * 3) = GetData(0x06)`
`v[3] = GetData(2 * (3 ^ 1 ^ 0 ^ 0)) = GetData(2 * 2) = GetData(0x04)`
etc...
I don't think there's any errors, but you could double check to make sure all the indicies are correct.

Initialize data in a loop

---

AziAudio/ABI3mp3.cpp
AziAudio/ABI_Adpcm.cpp
AziAudio/ABI_Buffers.cpp
AziAudio/ABI_Envmixer.cpp
AziAudio/ABI_Filters.cpp
AziAudio/ABI_Resample.cpp
AziAudio/HLEMain.cpp
AziAudio/audiohle.h
AziAudio/main.cpp

Instead of
```c
#define dmem    AudioInfo.DMEM
```
we also can do
```c
u8 * DMEM = AudioInfo.DMEM;
```
My personal preference is the latter, as this non-macro variant is a bit more protected against linguistic intervention by the C pre-processor.  For example, with the macro you can't name the define `DMEM` because that's recursive due to DMEM being also the name of the member of the AudioInfo struct.
I also think that writing "DMEM" instead of "dmem" is grammatically clearer (less likely to be confused for an abbreviation instead of an acronym, which almost always must be uppercase), though that's a separate issue.
This should have no effect on performance since it's just a pointer assigned to a pre-existing pointer, but I tested the changes with Conker's and Mario anyway.

Replace CPU-RSP memory macros with pointer names.

---

AziAudio/ABI_Filters.cpp

Faster actually, though that wasn't the intention.
The problem was the assert() I inserted a while back to check if outp[] fit in range of a s16 after:
```c
for (i = 0; i < 8; i++)
outp[i] = (s16)((out1[i] + 0x4000) >> 15); /* fractional round and shift */
```
Which was dumb because outp[] already was an array of s16's (plus the typecast), so the assert was useless for debugging.
I ended up forcing the signed clamp respective to VMULF to happen anyway, as there is no performance loss from doing so if you have SSE enabled.  In fact, vsats128() is even faster actually than just doing array16[i] = array32[i] & 0x0000FFFF; since no SIMD instruction on the Intel ISA corresponds to that.  So unintentionally this should have improved speed anyway.  Tested with OOT + MK64.

better clamping in ABI_Filters

---

AziAudio.vs2013.sln
AziAudio/AziAudio.vcxproj

Made the UIDs same for the VS2013 and VS2008 projects, set the VS2013 project to build for XP, fixed the debug output directory in VS2013, and cleaned up a few redundancies in the VS2013 project.

Visual Studio project cleanup

---

AziAudio/HLEMain.cpp
AziAudio/audiohle.h

To begin, I would like to point out that this plugin does work on 64-bit Project64 2.x, _with some changes_.
However because zilmar currently is a ![Slowpoke](http://www.froster.org/forum/style_emoticons/default/slowpoke.png) (sorry :D) with merging the more important, needed changes so that the upstream and official Project64 64-bit works, I have made [64-bit Project64 1.4](https://github.com/cxd4/Project64_64) here, which also works with this plugin.
When I pulled from master I just had to fix a couple build issues, and it works again.
There was a crash with Zelda MM in 64-bit audio HLE but that seems to have been fixed by pulling the commits I pushed a while back to fix the function pointer size memcpy'ing in the HLEMain function.  So it looks like this plugin pretty much works …

64-bit compilation fix (macro preprocessor regression caused by me)

---

AziAudio/ABI_Filters.cpp

Again something else I stumbled on accidentally while getting it to compile in the WDK with msvcrt.

fixed potential link-time collision with unoptimized m64p::`rdot`

---

make_wdk.cmd

https://github.com/Azimer/AziAudio/pull/110
Because Azimer mentioned wanting to investigate these changes in the future when he had time, I needed to push another commit to this (deleted) branch to fix the missing GUI resource script I neglected to test.  I'm merely recreating this branch in the form of a fresh pull request to avoid that confusion in case this does get investigated (and because deleting and recovering branches on GitHub didn't work the way I expected...).

added option to build using XP64-compatible WDK

---

AziAudio/DirectSoundDriver.cpp
AziAudio/DirectSoundDriver.h
AziAudio/Mupen64plusHLE/Mupen64Support.c

At first I was only trying to remove a couple `#pragma warning disable`'s and do more internal warning fixing, but then I discovered that in DirectSound builds of this plugin, there were tens of warnings left unattended so I also ended up fixing those.
I also ended up removing the #pragma warning disable around `#include <dsound.h>` because, /W4 in either 32- or 64-bit builds is not giving me any warnings??  Azimer maybe it's including a dsound.h other than the one the repository supplies and that is why you got warnings from including it.

more warning fixes

---

AziAudio/ABI_MixerInterleave.cpp

Seems to have been a bug since before AziAudio 0.55.1 old versions, as discussed here:  https://github.com/Azimer/AziAudio/issues/121
I don't know yet what parts of audio in what games this change fixes.

ADDMIXER:  fixed null function by adding writeback

---

AziAudio/HLEMain.cpp
AziAudio/audiohle.h

RSP doesn't work in terms of 8-byte vectors, so we don't need a 64-bit clamp function--with or without SSE or MMX.  I'm only removing this now because it used a 64-bit compiler intrinsic that older versions of MSVC (such as the Windows DDK build script I recently PR'd into this repo) do not recognize.  The dependency was unnecessary anyway since this function's very existence can give the misleading impression that it's useful for direct RSP emulation.

removed unused MMX clamp fallback

---

AziAudio/ABI_MixerInterleave.cpp
AziAudio/ABI_Resample.cpp

`pack_signed`, by definition of the RSP operation, already natively expects a parameter of type `s32` and returns a native result of type `s16`, so it's somewhat excessive to have explicit type casts to these types with regard to the function.

reduced explicit type conversions when calling pack_signed()

---

AziAudio/ABI_Buffers.cpp

Because `count &= 0xFFFC`, we know the precision for DMEM copies is 32-bit MIPS words, so I optimized the loops for accuracy in terms of the native addressing barrier.  Though in terms of speed I am sure these functions could be much faster still, but I would rather wait for the profiler to complain.

`count` always divisible by 4, so increment by 32-bit words.

---

AziAudio/DirectSoundDriver.h
AziAudio/common.h

fixes a possible compiler error from commit https://github.com/Azimer/AziAudio/commit/6b27f7a74928266853f8181740a4359a0612a0e7
At the least, GCC exposes this compiler error due to using the "3rd Party" folder for the DirectX includes, which conflicts with the pre-existing type definition of `typedef struct WAVEFORMATEXTENSIBLE`.  (The conflict happens between `<mmreg.h>` and "3rd Party" `<audiodefs.h>`.)

Fix possible [MinGW only?] build error when compiling DirectSound.

---

AziAudio/DirectSoundDriver.cpp
AziAudio/DirectSoundDriver.h
AziAudio/XAudio2SoundDriver.cpp
AziAudio/XAudio2SoundDriver.h

When I got the No Sound driver compiling on Linux it required changing the types away from stuff like WORD, DWORD, BYTE ... but this made it inconsistent with the C++ class types used in DirectSound/XAudio because C++ thinks `u32 (unsigned int)` can't be connected to `DWORD (unsigned long)`.
Simply changing the non-Linux code to say u32 instead of DWORD in this case fixes that, too.

fixed LLP64 ABI conflict confusing C++ between u32 and DWORD

---

AziAudio/audiohle.h

This commit fixes assemble-time errors with building AziAudio using GCC or MinGW.
The error arises when compiling with `masm=intel`, as AT&T is the default x86 syntax for GCC.
```
no@no-laptop:~/AziAudio$ ./make.sh
Compiling sources...
Assembling compiled sources...
./gccbuild/ABI3mp3.asm: Assembler messages:
./gccbuild/ABI3mp3.asm:1231: Error: invalid use of register
./gccbuild/ABI_Adpcm.asm: Assembler messages:
./gccbuild/ABI_Adpcm.asm:189: Error: invalid use of register
./gccbuild/ABI_Adpcm.asm:482: Error: invalid use of register
./gccbuild/ABI_Adpcm.asm:856: Error: invalid use of register
./gccbuild/ABI_Adpcm.asm:1130: Error: invalid use of register
./gccbuild/ABI_Adpcm.asm:1189: Error: invalid use of register
./gccbuild/ABI_Adpcm.asm:1248: Error: invalid use of register …
```

fixed GNU assembler error messages

---

AziAudio/SoundDriver.cpp

Stops sounds sometimes repeating forever when you reset with speed limiter off.

Fix reset audio with speed limiter off

---

AziAudio/main.cpp

Alright, my previous approach at a Linux build was a bit short-sighted.
While it does compile on Linux, I've underestimated the degree to which the AI and HLE functions all depend on the `snd` object to store a valid pointer to allocated sound driver class.  Simply keeping it NULL appears to not be an option that goes with the flow of Azimer's intended design.
So, I'm making this little change to attach NoSound driver #ifndef _WIN32 (includes _XBOX) as well.
Yes it will break compiling on Linux with a couple errors about WIN32-isms in the NoSound driver class, but I will be fine to tackle those based on whether these changes look acceptable.

Attach NoSound driver for non-Windows, non-Xbox builds.

---

AziAudio/NoSoundDriver.cpp
AziAudio/SDLSoundDriver.h
AziAudio/SoundDriver.cpp
AziAudio/SoundDriver.h
AziAudio/main.cpp

Okay, it took me a few days to get over the mental blocks involved, but I've decided on a temporary way to modify the new, anti-LEGACY_SOUND_DRIVER code in `SoundDriver.cpp` to be able to compile on Linux.  Most of the stuff being macro'd out there is about the Windows mutex object and the "wait for object" functions, for which I need to extract a suitable replacement in terms of SDL.
Not that I am any fan of SDL, but the fundamental design of this plugin's newer AI functions to use advanced timing and object functions would overwhelm me if I didn't at least begin to include it, for now.
Since I've already decided to attempt replacing the newer SoundDriver Win32 class code with SDL-ism's, I figured it seemed opportune to also start working on a SDLSoundDriver.cpp -- I have obviously not …

Finally get the plugin to actually run on Linux.

---

AziAudio.sln

Trivial change.
After removing the `$(Platform).$(Configuration).props` files, references to them were left on `AziAudio.sln`.

Remove reference to non-existing property sheets.

---

.gitignore
AziAudio/AziAudio.vcxproj

The produced DLL can be deployed to a provided Project64 installation.
Example:
`MSBuild AziAudio.sln /p:Configuration=Release /t:Publish /p:Pj64Install="C:\Games\Project64"`

Created Publish target.

---

AziAudio/DirectSoundDriver.cpp
AziAudio/DirectSoundDriver.h
AziAudio/SoundDriver.cpp
AziAudio/main.cpp

I meant to separate these fixes, but I merged them into one branch by mistake.
Note:  I made these fixes with the win32 hack for an ancient pre 1.5.2 jabo plugin removed from Project64, which calls main twice and creates an empty thread.  It hasn't been merged yet, but can be built from here:
https://github.com/Frank-74/project64/tree/Remove-pjutilDynLibCallDllMain()

Fix volume control and losing audio on plugin change and load savestate

---

AziAudio/main.cpp

A number of things being addressed:
1.  Calling `fread(azicfg, size, 1, file)` without a return value is bad.  That means if the config file was only 3, 2 or less than `size` bytes, no bytes would be imported at all.  Switching it around to `fread(azicfg, 1, size, file)` would have at least written what was available, but you should still check for the return value to see how many bytes were accessed without errors.
2.  Using `malloc` based on the file size of the config file could mistakenly allocate several GB of RAM if the config file name happened to represent some binary file other than the intended AziAudio configuration.  If Config/AziCfg.bin was really some other file just named wrongly and was say 4 GB in size, we'd really only need to malloc() just the first 4 bytes.
3.  Trying …

secure, simpler config file initialization

---

AziAudio/HLEMain.cpp
AziAudio/main.cpp

Shouldn't this be sufficient?
I didn't remember the //TODO comment being added here, but I think I had only declared the new DRAM, DMEM and IMEM pointers inside main.cpp just because that was what had the zilmar spec function InitiateAudio, which was the best place to initiate them from the Audio_Info.RDRAM etc. longer names.
But yes, anything related to the RDRAM stuff should only be relevant to the HLE audio code.

DRAM, DMEM and IMEM should be in HLEMain.

---

AziAudio/AudioSpec.h
AziAudio/Mupen64plusHLE/Mupen64Support.c
AziAudio/Mupen64plusHLE/common.h
AziAudio/common.h
Scripts/make.sh

I felt like doing some OCD clean-ups to the standards conformance of the code.
AziAudio compiles out of the box with the `-ansi` compiler switch in GCC.  This means that, when building the .c files, everything is backwards-compatible with the original C89 specification.  When building .cpp files, there's some other original version of the C++ specification being conformed to here.  (I don't know what it's called though because I really don't care about C++.)
The only exceptions were in zilmar's audio spec file and bsmiles audio code, which used the `inline` keyword (which is neither needed nor a part of the original C specs) and C++-style //comments.  Using C++-style comments in zilmar's audio spec header is fine when the AziAudio .cpp sources are including it, but when the bsmiles C code …

Now compiles with -ansi.

---

AziAudio/NoSoundDriver.h
Scripts/make.sh

So to get AziAudio to conform to standards and compile with `-ansi` required changing the bsmiles audio headers and zilmar's audio spec header.
To do likewise for being able to compile with `-pedantic` actually required only one single change...it was to code that I added myself as a quick hack to start trying to compile the NoSoundDriver class on Linux (which was using the LARGE_INTEGER win32 type, which I was trying to do a fast hack to emulate it on Linux in my experiments to get things to work.)
Once the NewAudio branch and other stuff by Azimer is merged in I will continue trying to get the plugin to run on Linux.  Getting everything ported now would be premature since some of the Win32 stuff is being replaced and/or under the deprecated legacy sound driver side, so in the meantime …

Now compiles with -pedantic.

---

AziAudio/Mupen64plusHLE/common.h
AziAudio/my_types.h

I never realized this, but `Boolean` was already typedef'd in `AziAudio/my_types.h`, making the copy in `AziAudio/Mupen64plusHLE/common.h` unnecessary.
GCC only warned about this when both -ansi **and** -pedantic are passed together, so it took me until both PRs being merged by Azimer for the warning to finally show up.

fixed warning: redefinition of typedef 'Boolean' [-Wpedantic]

---

AziAudio/Mupen64plusHLE/memory.c
AziAudio/Mupen64plusHLE/memory.h
Scripts/make.sh

Adding `-Wall` has introduced many warnings in the compile output.  A few of them look like they could be bugs...but right now in this PR I am only focusing on the most tedious, repetitive warning:
"unused function".  It's due to bsmiles' memory.h making static definitions of functions from inside the header.  Any .c file that includes memory.h must use all of those functions or else ignore code cleanliness warnings, which I don't really see a cause for bypassing.
Once I can get the spamming of these warnings out of the way, I can focus on the less trivial ones.
```
In file included from ./../AziAudio/Mupen64plusHLE/memory.c:24:0:
./../AziAudio/Mupen64plusHLE/memory.h:77:25: note: previous definition of 'pt_u32' was here
static inline uint32_t* pt_u32(const unsigned char* buffer, unsigned …
```

Start compiling with all warnings enabled.

---

AziAudio/ABI_Adpcm.cpp

```
./../AziAudio/ABI_Adpcm.cpp: In function 'void ADPCM2()':
./../AziAudio/ABI_Adpcm.cpp:309:5: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
if (!(Flags & 0x1))
^
./../AziAudio/ABI_Adpcm.cpp:302:5: warning: variable 'inpinc' set but not used [-Wunused-but-set-variable]
u8 inpinc;
^
./../AziAudio/ABI_Adpcm.cpp: In function 'void ADPCM3()':
./../AziAudio/ABI_Adpcm.cpp:423:5: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
if (!(Flags & 0x1))
^
```

warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]

---

AziAudio/Mupen64plusHLE/musyx.c

```
./../AziAudio/Mupen64plusHLE/musyx.c:848:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
#pragma warning(disable : 4100)
^
./../AziAudio/Mupen64plusHLE/musyx.c:860:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
#pragma warning(default : 4100)
^
```

warning: ignoring #pragma warning  [-Wunknown-pragmas]

---

AziAudio/SoundDriver.cpp

```
./../AziAudio/SoundDriver.cpp: In member function 'void SoundDriver::AI_ResetAudio()':
./../AziAudio/SoundDriver.cpp:170:40: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
m_audioIsInitialized = (!Initialize() == TRUE);
^
```

warning: logical NOT applied to left side only [-Wlogical-not-parentheses]

---

AziAudio/ABI_Envmixer.cpp

```
In file included from ./../AziAudio/ABI_Envmixer.cpp:15:0:
./../AziAudio/ABI_Envmixer.cpp: In function 'void ENVMIXER3()':
./../AziAudio/audiohle.h:78:17: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
#define k0      GPR_k0
^
./../AziAudio/ABI_Envmixer.cpp:521:24: note: in expansion of macro 'k0'
Vol_Right = (*(s16 *)&k0);
^
./../AziAudio/ABI_Envmixer.cpp: In function 'void SETVOL()':
./../AziAudio/audiohle.h:78:17: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
#define k0      GPR_k0
^
./../AziAudio/ABI_Envmixer.cpp:638:27: note: in expansion of macro 'k0'
VolTrg_Left = *(s16 *)&k0;
^
./../AziAudio/audiohle.h:78:17: warning: dereferencing type-punned pointer will break strict-aliasing …
```

warning:  dereferencing type-punned ptr breaks aliasing rules [Wstrict-aliasing]

---

AziAudio/NoSoundDriver.cpp
AziAudio/SoundDriver.h

...and this should be the last of them.
Everything compiles now under -Wall with no warnings at all except only for two remaining warnings I won't try to fix by myself.  https://github.com/Azimer/AziAudio/issues/171 and https://github.com/Azimer/AziAudio/issues/172
Warnings fixed in this PR:
```
In file included from ./../AziAudio/SDLSoundDriver.h:14:0,
from ./../AziAudio/main.cpp:20:
./../AziAudio/SoundDriver.h: In member function 'virtual void SoundDriver::AiUpdate(Boolean)':
./../AziAudio/SoundDriver.h:58:68: warning: statement has no effect [-Wunused-value]
virtual void AiUpdate(Boolean Wait) { UNREFERENCED_PARAMETER(Wait); }; // Optional
^
./../AziAudio/SoundDriver.h: In member function 'virtual void SoundDriver::SetVolume(u32)':
./../AziAudio/SoundDriver.h:84:69: warning: statement …
```

unused variable warnings

---

AziAudio/SoundDriver.cpp

This is just a continuity of https://github.com/Azimer/AziAudio/pull/168 .
Not sure what happened.  This looks like the warning that was originally reported, but I fixed it for the copy of the call under LEGACY_SOUND_DRIVER.  There were actually two cases of (!Initialize() == TRUE) throughout the file; they should both be fixed now.

replicated order-of-operations warning fix in AI_ResetAudio()

---

AziAudio/common.h

```
In file included from ./../AziAudio/audiohle.h:12:0,
from ./../AziAudio/ABI1.cpp:12:
./../AziAudio/common.h:168:35: error: 'size_t' has not been declared
extern int safe_strcpy(char* dst, size_t limit, const char* src);
^
In file included from ./../AziAudio/AudioSpec.h:18:0,
from ./../AziAudio/audiohle.h:83,
from ./../AziAudio/ABI1.cpp:12:
./../AziAudio/common.h:168:35: error: 'size_t' has not been declared
extern int safe_strcpy(char* dst, size_t limit, const char* src);
^
In file included from ./../AziAudio/audiohle.h:12:0,
from ./../AziAudio/ABI2.cpp:12:
./../AziAudio/common.h:168:35: error: 'size_t' has not been declared
extern int safe_strcpy(char* dst, size_t limit, const char* src);
^
In file included from ./../AziAudio/AudioSpec.h:18:0,
from ./../AziAudio/audiohle.h:83,
from …
```

included stddef.h to always define size_t

---

AziAudio/main.cpp

```
./../AziAudio/main.cpp:133:52: error: 'memcpy' was not declared in this scope
memcpy(&AudioInfo, &Audio_Info, sizeof(AUDIO_INFO));
^
./../AziAudio/main.cpp:144:52: error: 'strcpy' was not declared in this scope
strcpy(Configuration::configAudioLogFolder, "D:\\");
^
./../AziAudio/main.cpp: In function 'int safe_strcpy(char*, size_t, const char*)':
./../AziAudio/main.cpp:431:23: error: 'strlen' was not declared in this scope
bytes = strlen(src) + 1; /* strlen("abc") + 1 == 4 bytes */
^
./../AziAudio/main.cpp:438:27: error: 'memcpy' was not declared in this scope
memcpy(dst, src, bytes);
^
```

included string.h to declare memcpy() and strcpy()

---

AziAudio/Configuration.cpp

Defaults weren't saved if AziCfg.bin didn't exist.

Fix default config settings.

---

AziAudio/Configuration.cpp

```
./../AziAudio/Configuration.cpp:3:21:
fatal error:  Windows.h:  No such file or directory
compilation terminated.
```

windows.h:  no such file or directory

---

AziAudio/Configuration.h

```
In file included from ./../AziAudio/SoundDriverInterface.h:4:0,
from ./../AziAudio/main.cpp:15:
./../AziAudio/Configuration.h: In static member function 'static char* Configuration::getAudioLogFolder()':
./../AziAudio/Configuration.h:41:38: error: 'strcpy' was not declared in this scope
strcpy(retVal, configAudioLogFolder);
^
./../AziAudio/Configuration.h: In static member function 'static char* Configuration::getDevice()':
./../AziAudio/Configuration.h:46:30: error: 'strcpy' was not declared in this scope
strcpy(retVal, configDevice);
^
In file included from ./../AziAudio/SoundDriverInterface.h:4:0,
from ./../AziAudio/SoundDriverFactory.h:2,
from ./../AziAudio/SoundDriverFactory.cpp:2:
In file included from ./../AziAudio/SoundDriverInterface.h:4:0,
from …
```

strcpy() not declared in this scope

---

.gitignore

These files popped up in my working Git stage list when using WINE console to cross-compile the Windows build of AziAudio using the Windows DDK on Linux.

Keep binary files resource.res and vc90.idb out.
